## Ability trigger prefixes
prefix-left-click: "&e[Left Click] &7"  # Used for items
prefix-right-click: "&e[Right Click] &7"  # Used for food and drinks

## Available abilities that can be applied to items and food
## command-console is run on the console and replaces:
## [playerName] with the name of the user
abilities:
    heal:
        name: "Healing Touch"
        description: "Heals the user"
        icon-material: "jigsaw"
        icon-custom-model-data: 1
        command-console: "effect give [playerName] instant_health 1 1"
        charges: 10
        stack-size: 5
        cooldown: 5000  # 5 second cooldown
        allowed-types: ["FOOD", "DRINK"]  # Both food and drinks can heal
    lightning:
        name: "Lightning Strike"
        description: "Strikes lightning at the user"
        icon-material: "jigsaw"
        icon-custom-model-data: 2
        command-console: "cmi lightning [playerName]"
        charges: 5
        stack-size: 3
        cooldown: 2000  # 2 second cooldown
        allowed-types: ["ITEM"]  # Only items can strike lightning
    speed_boost:
        name: "Speed Boost"
        description: "Gives a temporary speed boost when used"
        icon-material: "jigsaw"
        icon-custom-model-data: 3
        command-console: "effect give [playerName] speed 30 2"
        charges: 25
        stack-size: 2
        cooldown: 500  # Default 500ms cooldown
        allowed-types: ["ITEM", "FOOD", "DRINK"]  # All types can give speed

## Available icons for items
item-icons:
    diamond_sword:
        - "1-5"
    netherite_sword:
        - "1-3"
    stick:
        - "1"
        - "5-7"

## Available icons for food items
food-icons:
    apple:
        - "1-3"
    golden_apple:
        - "1-2"
    cookie:
        - "1-5"
    bread:
        - "1"
        - "3-4"

## Available icons for drink items
drink-icons:
    apple:
        - "1-3"
    golden_apple:
        - "1-2"
    cookie:
        - "1"
    bread:
        - "1-4" 